with open(r'C:\Users\anaco\OneDrive\Desktop\Nueva carpeta\fix_palmira_passwords.js', 'w', encoding='utf-8') as f:
    f.write('const bcrypt = require("bcrypt");\n')
    f.write('const { Client } = require("pg");\n\n')
    f.write('async function main() {\n')
    f.write('  const hash = await bcrypt.hash("22222", 10);\n')
    f.write('  const client = new Client({ host: "db", port: 5432, user: "postgres", password: "alejo.v02", database: "sena_db" });\n')
    f.write('  await client.connect();\n')
    f.write('  await client.query("UPDATE cg_usuarios SET password = $1 WHERE correo IN ($2, $3)", [hash, "aprendiz@palmira.com", "instructor@palmira.com"]);\n')
    f.write('  await client.end();\n')
    f.write('  console.log("HASH", hash);\n')
    f.write('  console.log("OK");\n')
    f.write('}\n')
    f.write('main().catch(e => { console.error(e); process.exit(1); });\n')
print('archivo escrito')
